# This is the configuration file for GitHub's Dependabot, used here for version updates.
# See the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot
# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2

registries:
  phylum:
    type: python-index
    url: https://pypi.phylum.io/simple/
    username: Phylum%2FPhylum
    password: ${{ secrets.PHYLUM_TOKEN }}
    replaces-base: true

updates:
  # "pip" also covers Poetry
  - package-ecosystem: "pip"
    registries:
      - phylum
    # Allowing external code execution is required for Dependabot to update the
    # "pip" ecosystem when a custom external registry is specified. Reference:
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#allowing-external-code-execution
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
    # Only worry about major version updates here. Other updates are accounted for in
    # a separate workflow in an effort to reduce the number of PRs opened by Dependabot.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      # The `python-semantic-release` package is pinned in `pyproject.toml` and
      # should not be updated until all the breaking changes are considered.
      # TODO: Remove this entry
      #       https://github.com/phylum-dev/phylum-ci/issues/565
      - dependency-name: "python-semantic-release"
        update-types: ["version-update:semver-major"]

  # All GitHub actions should be pinned to an explicit SHA instead of a tag name.
  # Each pin should include a comment about the version of the action to which it corresponds.
  # Dependabot will update these comments at the same time that it updates the pin.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
