# This is the config for defining `pre-commit` hooks for use in other repositories.
#
# See https://pre-commit.com for more information
---
- id: phylum
  name: analyze dependencies with phylum
  description: Run `phylum` on dependency files
  entry: phylum-ci
  language: python
  stages: [commit]
