# This is a workflow for updating Python dependencies with Poetry.
# Major version updates are handled separately, by Dependabot.
# It will also update the pre-commit hooks to use latest tags.
---
name: Update Deps

on:
  workflow_dispatch:
  # Run every Monday at 0335 UTC
  schedule:
    - cron: '35 3 * * 1'

jobs:
  workflow-auto-updates:
    name: Update dependencies and hooks
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.13"
      POETRY_VERSION: "2.1.3"
      UPDATE_BRANCH_NAME: workflow-auto-updates
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # This GPG key is for the `phylum-bot` account and used in order to ensure commits are signed/verified
      - name: Import GPG key for bot account
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.PHYLUM_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PHYLUM_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Install poetry
        run: |
          pipx install \
            --index-url "https://Phylum%2FPhylum:${{ secrets.PHYLUM_TOKEN }}@pypi.phylum.io/simple/" \
            poetry==${{ env.POETRY_VERSION }}

      - name: Configure poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config http-basic.phylum "Phylum%2FPhylum" "${{ secrets.PHYLUM_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Install the project with poetry
        run: |
          poetry env use python${{ env.PYTHON_VERSION }}
          poetry check --lock --strict
          poetry lock --no-cache
          poetry sync --verbose --no-root --with qa

      # Update hooks before dependencies because otherwise `pre-commit` may be updated and used before it can be trusted
      #
      # NOTE: Specific repos are specified for update since the autoupdated/frozen version here may not always be the
      # latest version. This is the case for `poetry`, which has described the limitations of `pre-commit` here:
      # https://python-poetry.org/docs/pre-commit-hooks/#why-does-pre-commit-autoupdate-not-update-to-the-latest-version
      # Consider using the `pre-commit-update` package here instead: https://pypi.org/project/pre-commit-update/
      - name: Update pre-commit hooks
        run: |
          poetry run pre-commit autoupdate --freeze \
          --repo https://github.com/pre-commit/pre-commit-hooks \
          --repo https://github.com/psf/black \
          --repo https://github.com/charliermarsh/ruff-pre-commit \
          --repo https://github.com/dosisod/refurb \
          --repo https://github.com/jendrikseipp/vulture \
          --repo https://github.com/adrienverge/yamllint

      - name: Update Python dependencies
        run: |
          poetry update -vv --lock --no-cache
          poetry check --lock --strict

      - name: Commit changes
        id: commit
        # There may not be any updates to commit/push
        continue-on-error: true
        # NOTE: The git user name and email used for commits is already configured,
        #       by the crazy-max/ghaction-import-gpg action.
        run: |
          git commit -a -m "build: bump \`poetry.lock\` dependencies and \`pre-commit\` hooks"
          git push --force origin HEAD:${{ env.UPDATE_BRANCH_NAME }}

      - name: Create Pull Request
        id: pr
        if: ${{ steps.commit.outcome == 'success' }}
        # The PR may already exist (e.g., created in previous week and not merged yet) so we
        # allow it here and check in the next step so workflow failures will be extraordinary
        continue-on-error: true
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          # This PAT is for the `phylum-bot` account and only has the `public_repo` scope to limit privileges.
          github-token: ${{ secrets.GH_RELEASE_PAT }}
          script: |
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "${{ env.UPDATE_BRANCH_NAME }}",
              base: context.ref,
              title: "build: bump `poetry.lock` dependencies and `pre-commit` hooks",
              body: "Bump dependencies in `poetry.lock` and hooks in `.pre-commit-config.yaml`.",
            });
            console.log(response);

      - name: Verify PR exists
        if: ${{ steps.pr.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr view ${{ env.UPDATE_BRANCH_NAME }}
