name: Add issues to main project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/phylum-dev/projects/24
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
