# This is a workflow for updating Python dependencies with Poetry.
# Major version updates are handled separately, by Dependabot.
---
name: Update Deps

on:
  workflow_dispatch:
  # Run every Monday at 1435 UTC
  schedule:
    - cron: '35 14 * * 1'

jobs:
  poetry-update:
    name: Update Python dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # It's only one Python version specified in a "matrix", but on purpose to stay DRY
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      # TODO: Use a "CI" group to ensure only the dependencies needed for running in the CI environment are installed.
      #       This should be possible when Poetry 1.2 is available, using the groups feature:
      #       https://github.com/python-poetry/poetry/issues/1644
      #       https://github.com/phylum-dev/phylum-ci/issues/15
      - name: Install the project with poetry
        run: |
          poetry env use python${{ matrix.python-version }}
          poetry install --verbose --no-root

      - name: Poetry update
        run: poetry update -vv

      - name: Commit changes
        id: commit
        continue-on-error: true
        run: |
          git config user.name 'Phylum Bot'
          git config user.email 'phylum-bot@users.noreply.github.com'
          git commit -a -m "build: Bump poetry.lock dependencies"
          git push --force origin HEAD:auto-poetry-update

      - name: Create Pull Request
        if: ${{ steps.commit.outcome == 'success' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "auto-poetry-update",
              base: context.ref,
              title: "build: Bump poetry.lock dependencies",
              body: "Bump dependencies in poetry.lock for all SemVer-compatible updates.",
            });
